import React from 'react';
import {
  Modal,
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  Share,
  Alert
} from 'react-native';
import Icon from '../../components/common/AppIcon';
import { useAppTheme } from '../../theme/useAppTheme';

type Props = {
  visible: boolean;
  onClose: () => void;
  baby: any;
  growthLogs: any[];
};

export const BabyGrowthReportModal: React.FC<Props> = ({ visible, onClose, baby, growthLogs }) => {
  const { colors, isDark } = useAppTheme();

  if (!baby) return null;

  const latestLog = growthLogs && growthLogs.length > 0 ? growthLogs[0] : null;

  const handleExportPDFReport = async () => {
    try {
      const logsText = growthLogs && growthLogs.length > 0
        ? growthLogs.map((l: any, i: number) =>
            `${i + 1}. Date: ${new Date(l.recordedAt || l.date).toLocaleDateString()} | Height: ${l.heightCm || l.height || '—'} cm | Weight: ${l.weightKg || l.weight || '—'} kg | Head: ${l.headCircumferenceCm || '—'} cm`
          ).join('\n')
        : 'No growth records logged yet.';

      const reportContent =
        `=========================================\n` +
        `   BABYNUTRI PEDIATRIC GROWTH REPORT     \n` +
        `=========================================\n` +
        `Baby Name: ${baby.name}\n` +
        `Date of Birth: ${new Date(baby.dateOfBirth).toLocaleDateString()}\n` +
        `Gender: ${baby.gender || 'Not specified'}\n` +
        `Assessment Date: ${new Date().toLocaleDateString()}\n\n` +
        `LATEST MEASUREMENTS (WHO Standard):\n` +
        `• Current Height: ${latestLog?.heightCm || latestLog?.height || '—'} cm\n` +
        `• Current Weight: ${latestLog?.weightKg || latestLog?.weight || '—'} kg\n` +
        `• Current Head Circumference: ${latestLog?.headCircumferenceCm || '—'} cm\n\n` +
        `GROWTH HISTORY LOGS:\n${logsText}\n` +
        `=========================================\n` +
        `Generated by BabyNutri Health App`;

      await Share.share({
        title: `Baby Growth Report - ${baby.name}`,
        message: reportContent,
      });
    } catch (e: any) {
      Alert.alert('Export Error', e.message || 'Unable to share report.');
    }
  };

  return (
    <Modal visible={visible} animationType="slide" transparent={false} onRequestClose={onClose}>
      <View style={[styles.container, { backgroundColor: colors.background }]}>
        {/* Header */}
        <View style={[styles.header, { borderColor: colors.border }]}>
          <Text style={[styles.headerTitle, { color: colors.text }]}>Pediatric Growth Report</Text>
          <TouchableOpacity style={styles.closeBtn} onPress={onClose}>
            <Icon source="close" size={24} color={colors.text} />
          </TouchableOpacity>
        </View>

        <ScrollView contentContainerStyle={styles.content}>
          {/* Baby Card Banner */}
          <View style={[styles.babyCard, { backgroundColor: isDark ? '#2E2836' : '#FFF0F2', borderColor: '#FF5F70' }]}>
            <View style={styles.avatarCircle}>
              <Text style={styles.avatarText}>{baby.name.charAt(0).toUpperCase()}</Text>
            </View>
            <View style={styles.babyInfo}>
              <Text style={[styles.babyName, { color: colors.text }]}>{baby.name}</Text>
              <Text style={[styles.babySub, { color: colors.textSoft }]}>
                DOB: {new Date(baby.dateOfBirth).toLocaleDateString()} • {baby.gender || 'Baby'}
              </Text>
              <View style={styles.whoBadge}>
                <Icon source="shield-check-outline" size={14} color="#10B981" />
                <Text style={styles.whoBadgeText}>WHO Pediatric Growth Standard</Text>
              </View>
            </View>
          </View>

          {/* Latest Assessment Grid */}
          <Text style={[styles.sectionHeading, { color: colors.text }]}>Latest Measurement Summary</Text>
          <View style={styles.grid}>
            <View style={[styles.gridCard, { backgroundColor: isDark ? '#1E293B' : '#EFF6FF' }]}>
              <Icon source="ruler" size={22} color="#3B82F6" />
              <Text style={styles.gridVal}>{latestLog?.heightCm || latestLog?.height || '—'} cm</Text>
              <Text style={styles.gridLabel}>Height</Text>
            </View>

            <View style={[styles.gridCard, { backgroundColor: isDark ? '#3A2E31' : '#FFF0F2' }]}>
              <Icon source="scale-bathroom" size={22} color="#FF5F70" />
              <Text style={styles.gridVal}>{latestLog?.weightKg || latestLog?.weight || '—'} kg</Text>
              <Text style={styles.gridLabel}>Weight</Text>
            </View>

            <View style={[styles.gridCard, { backgroundColor: isDark ? '#2B3830' : '#ECFDF5' }]}>
              <Icon source="tape-measure" size={22} color="#10B981" />
              <Text style={styles.gridVal}>{latestLog?.headCircumferenceCm || '—'} cm</Text>
              <Text style={styles.gridLabel}>Head Circumference</Text>
            </View>
          </View>

          {/* Growth Logs Table */}
          <Text style={[styles.sectionHeading, { color: colors.text, marginTop: 22 }]}>Growth Records History</Text>
          {growthLogs && growthLogs.length > 0 ? (
            <View style={[styles.table, { backgroundColor: colors.surface, borderColor: colors.border }]}>
              <View style={styles.tableHeaderRow}>
                <Text style={[styles.th, { color: colors.text }]}>Date</Text>
                <Text style={[styles.th, { color: colors.text }]}>Height</Text>
                <Text style={[styles.th, { color: colors.text }]}>Weight</Text>
                <Text style={[styles.th, { color: colors.text }]}>Head</Text>
              </View>
              {growthLogs.map((log: any, idx: number) => (
                <View key={idx} style={[styles.tableRow, { borderColor: colors.border }]}>
                  <Text style={[styles.td, { color: colors.textSoft }]}>
                    {new Date(log.recordedAt || log.date).toLocaleDateString()}
                  </Text>
                  <Text style={[styles.tdBold, { color: colors.text }]}>{log.heightCm || log.height || '—'} cm</Text>
                  <Text style={[styles.tdBold, { color: colors.text }]}>{log.weightKg || log.weight || '—'} kg</Text>
                  <Text style={[styles.td, { color: colors.textSoft }]}>{log.headCircumferenceCm || '—'} cm</Text>
                </View>
              ))}
            </View>
          ) : (
            <Text style={{ color: colors.textSoft, fontSize: 13, marginVertical: 10 }}>No measurement logs recorded yet.</Text>
          )}

          {/* Export Button */}
          <TouchableOpacity style={styles.exportBtn} onPress={handleExportPDFReport} activeOpacity={0.88}>
            <Icon source="file-document-outline" size={20} color="#FFFFFF" />
            <Text style={styles.exportBtnText}>Export Health Report (PDF / Printable)</Text>
          </TouchableOpacity>
        </ScrollView>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, paddingTop: 50 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
  },
  headerTitle: { fontSize: 18, fontWeight: '800' },
  closeBtn: { padding: 4 },
  content: { padding: 18, paddingBottom: 60 },
  babyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
    marginBottom: 20,
    gap: 14,
  },
  avatarCircle: { width: 54, height: 54, borderRadius: 27, backgroundColor: '#FF5F70', justifyContent: 'center', alignItems: 'center' },
  avatarText: { color: '#FFFFFF', fontSize: 22, fontWeight: '800' },
  babyInfo: { flex: 1 },
  babyName: { fontSize: 18, fontWeight: '800' },
  babySub: { fontSize: 12, marginTop: 2 },
  whoBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 6 },
  whoBadgeText: { fontSize: 11, fontWeight: '700', color: '#10B981' },
  sectionHeading: { fontSize: 15, fontWeight: '800', marginBottom: 12 },
  grid: { flexDirection: 'row', gap: 10 },
  gridCard: { flex: 1, borderRadius: 14, padding: 12, alignItems: 'center' },
  gridVal: { fontSize: 16, fontWeight: '800', marginTop: 6, marginBottom: 2 },
  gridLabel: { fontSize: 11, fontWeight: '600', color: '#4B3034' },
  table: { borderRadius: 16, borderWidth: 1, overflow: 'hidden' },
  tableHeaderRow: { flexDirection: 'row', backgroundColor: '#F3F4F6', paddingVertical: 10, paddingHorizontal: 12 },
  th: { flex: 1, fontSize: 12, fontWeight: '800' },
  tableRow: { flexDirection: 'row', paddingVertical: 12, paddingHorizontal: 12, borderTopWidth: 1 },
  td: { flex: 1, fontSize: 12 },
  tdBold: { flex: 1, fontSize: 12, fontWeight: '700' },
  exportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FF5F70',
    paddingVertical: 14,
    borderRadius: 16,
    marginTop: 26,
  },
  exportBtnText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
});

export default BabyGrowthReportModal;
